### ISSUE TITLE
Slow incremental builds using `xcodebuild`

### ISSUE THREAD

**Issue by wojciech-kulik** [wojciech-kulik/xcodebuild.nvim#201]
Recently, I discovered that adding `CODE_SIGNING_ALLOWED=NO"` to `xcodebuild` commands significantly speeds up incremental builds. However, the problem is that you can't run the app built this way, because obviously it's unsigned.

I suspect that `xcodebuild` signing process is for some reason very slow, so if we could figure out a way to sign in afterwards, maybe we could speed up builds. Unfortunately, I haven't yet found a way to sign the app.

So far I tried:
```
codesign --force --deep --sign "Apple Development: John Snow (XYZ)" /Users/wkulik/Library/Developer/Xcode/DerivedData/XYZ-hblnhsksxjrctzekqmlevcflnsji/Build/Products/Debug-iphonesimulator/XYZ.app
```

and also signing all frameworks and bundles before signing the whole app, but it doesn't work - the app can't be launched.

**Comment by wojciech-kulik** [comment]
I discovered the problem. It turns out that the issue is caused by the way the `xcodebuild` tool handles signing. It performs multiple requests to `developerservices2.apple.com` API which take over 20 seconds each time you run a build 🤦‍♂️

![apple2](https://github.com/user-attachments/assets/ef7d1acc-fb0f-49cc-82c8-a3f6e1391d6f)

It's a very inefficient behavior, but unfortunately, I don't think it's possible to fix or configure it on our side. We need to wait for a fix provided by Apple, possibly to cache those responses. I have already created a ticket in Feedback Assistant: **FB15478221**.

However, there is also good news, we can speed up builds by temporarily blocking that domain. In my case, it speeds up an incremental build from 30 seconds down to 10 seconds. Below you will find details on how to do that.

> [!CAUTION]
> Blocking that domain will most likely result in disabling some Xcode functions like automatic registering devices, capabilities, etc. Therefore, it's best to enable it when you are working on code and you don't need any modifications related to signing or capabilities.

## Solution 1
1. Open terminal.
2. Run `sudo vim /etc/hosts`.
3. Append:
    ```
    127.0.0.1 developerservices2.apple.com
    ```
4. Save & quit.

## Solution 2
If you use some tool to sniff network traffic like Proxyman or Charles Proxy, you can block requests to `https://developerservices2.apple.com/*` and automatically return some error like 999 status code. It will prevent `xcodebuild` from further calls.

**Comment by Almaz5200** [comment]
<img width="1134" alt="Screenshot 2024-10-19 at 3 31 46 PM" src="https://github.com/user-attachments/assets/7ce592f6-d331-4323-bd77-9debfedddef2">
Yeah, definetly helped me too, but the change is not as drastic. It went from 27 seconds on average to 18 seconds. I see that for you it makes four of each requests, however I only see one of them. Which Xcode version do you use? Could it be that they improved it at a later version? Mine is 16.0

**Comment by wojciech-kulik** [comment]
I use Xcode 16.0. It looks like it might be connected with the number of targets in the project. I've got the main target + 3 extensions. The funny thing is that each request is exactly the same very poor optimization

**Comment by Almaz5200** [comment]
Yeah, and that would explain the fact that you've seen more improvement than I did as well. The project I've tested on doesn't have any extensions

**Comment by rudrankriyam** [comment]
I found it mentioned in the [developer forums](https://forums.developer.apple.com/forums/thread/756120) and the difference is evident when you turn off the internet and see it does not hang on `GatherProvisioningInputs` anymore

**Comment by marcusziade** [comment]
can confirm

**Comment by wojciech-kulik** [comment]
I'm working to integrate an automatic script to disable `developerservices2.apple.com` domain during build based on @rudrankriyam's code: https://x.com/rudrankriyam/status/1847734299740811675 to make it simpler to use without the need to manually turn on & off the workaround.

**Comment by wojciech-kulik** [comment]
The script to automate applying the workaround has been integrated with xcodebuild.nvim. 

Here is the instruction explaining how to enable this feature: 
https://github.com/wojciech-kulik/xcodebuild.nvim/wiki/Tips-&-Tricks#%EF%B8%8Fimprove-build-time

Don't forget to update the plugin first :)!

**Comment by LionWY** [comment]
follow

**Comment by NachoSoto** [comment]
Does it also try to make those requests if you completely disable signing?

**Comment by kambala-decapitator** [comment]
> Unfortunately, I haven't yet found a way to sign the app

Looks like your codesign command is incorrect - you forgot entitlements for the app.

Correct sign workflow is:
1. For watch app and all extensions: first sign all frameworks, then sign the executable (or its bundle) with respective entitlements 
2. Sign all app frameworks 
3. Sign the main app with respective entitlements

You can also check the codesign command that xcodebuild issues in Xcode build log or in the command line invocation (just don't pass -quiet for the latter).

**Comment by simpers** [comment]
Does tuist also suffer from this? As far as I can see, running `tuist build ...` sets up an `xcodebuild` process so unless they also have a workaround for this, it affects them too.

Is this a new Xcode 16.x thing or has it always been like this? I haven't paid enough attention to build times using tuist only as I've mostly used it for cold builds.

Since this project is the first time I tried to work outside of Xcode – where remote work over SSH is the real benefit for me – I haven't been able to assess these things until now.

**Comment by wojciech-kulik** [comment]
@simpers If tuist uses xcodebuild without any hacks then most likely it affects them too. 

I’m not sure if it was introduced at some point, but for sure Xcode 15 & 16 are affected.

**Comment by wojciech-kulik** [comment]
Pinned & closed as there is nothing to be done on plugin's side to fix that.

**Comment by FelixLisczyk** [comment]
It looks like this issue is finally fixed in Xcode 26.0. An incremental `xcodebuild` (second run) in an empty project now takes about 1 second on my machine without any modifications to network rules.

**Comment by wojciech-kulik** [comment]
Great news, I'll test it soon!

**Comment by wojciech-kulik** [comment]
I ran some tests and can confirm that with Xcode 26, `xcodebuild` now works just as fast as Xcode 16 with the workaround.

This is true both when rebuilding the app without any changes and when performing incremental builds after making changes.

I also noticed that Xcode 26 no longer calls the slow `developerservices2.apple.com`. Instead, it uses `https://ocsp2.apple.com`, which is much faster.

🎊 🎊 🎊

**Comment by wojciech-kulik** [comment]
Therefore, when using Xcode 26 the workaround isn't needed anymore. You can safely remove the integration from your config:

```
integrations = {
  xcodebuild_offline = {
    enabled = true,
  },
}
```

The plugin will use the default `false` value and the workaround won't be applied anymore.

**Comment by wojciech-kulik** [comment]
I was too optimistic about Apple. As usual, they did something but they didn't fix the problem completely 🤦 ... It turns out that they implemented a weird cache that works only per terminal session, so when I spawn a new job to get build settings or devices, it doesn't use the cache...

Here is my sample scenario:

```
1. Start terminal
2. Run: time xcodebuild -project MyProject.xcodeproj -scheme MyProject -showBuildSettings -sdk iphonesimulator (takes around ~14s)
3. Run again the same command (takes around ~2s).
4. Open a new terminal window and run the command again (takes around ~14s).
```

I've already submitted it to Apple, but probably we'll wait another couple of years...

You can observe this issue when switching between a real device and a simulator - retrieving build settings takes a while.

**Comment by wojciech-kulik** [comment]
I discovered that all `xcodebuild` commands waste time one on `Resolve Package Graph` step. In my case it takes around 15-20 seconds... I tried skipping it by adding additional params but nothing helps:
```
xcodebuild -project XYZ.xcodeproj -scheme XYZ -sdk iphonesimulator -onlyUsePackageVersionsFromResolvedFile -skipPackageUpdates -disableAutomaticPackageResolution -skipPackageSignatureValidation
```

I'm not sure how it happened that it worked well before. Maybe I tested it on a project without Swift packages? I'm not sure. I even downloaded Xcode 26.0.1 and the same problem occurs there.

So now incremental builds, even if nothing is changed, take extra 15-20 seconds...

Could you guys check if you experience the same problem?

**Comment by wojciech-kulik** [comment]
I think I've found the root cause. The "Resolve Package Graph" step becomes significantly slower when the Firebase Swift Package is included. Without Firebase, it takes about ~1s, with Firebase, it increases to ~19s.

I've reported this as a bug here: https://github.com/firebase/firebase-ios-sdk/issues/15649

**Comment by wojciech-kulik** [comment]
I tired older package versions as well and the duration was the same. Could you try downgrading the version in the sample project to 11.12.0 and see if it changes anything?

**Comment by wojciech-kulik** [comment]
That's very interesting. I suspect that it might a build setting, targeted SDK, or something like that. I'll play with project settings and see if I can affect it. Thanks for your input! 🍻

**Comment by wojciech-kulik** [comment]
One more question. In your project, the one that is resolved fast, do you see "Swift Protobuf" as a dependency on the list of packages? If so, what version you have there?
